services:
  db:
    image: mysql:8.0
    container_name: fit4110-db-lab05
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_campus
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - team-internal

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fit4110-api-lab05
    restart: always
    ports:
      - "8000:8000"
    environment:
      - AUTH_TOKEN=smart-campus-secret-token
    command: ["/opt/venv/bin/uvicorn", "src.iot_app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - class-net
      - team-internal
    depends_on:
      - db

networks:
  class-net:
    external: true
  team-internal:
    driver: bridge

volumes:
  db-data:
